# Generated by Django 3.2.7 on 2021-10-13 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionLocales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('cod_notificacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dui', models.BigIntegerField(blank=True, null=True)),
                ('visto', models.BigIntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.DateField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('dui', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nit', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_dui', models.BigIntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('codigo_docente', models.CharField(max_length=20)),
                ('cod_escuela', models.ForeignKey(db_column='cod_escuela', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionLocales.escuela')),
            ],
            options={
                'db_table': 'docente',
                'managed': True,
                'unique_together': {('dui', 'emp_dui')},
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('dui', models.BigIntegerField(primary_key=True, serialize=False)),
                ('emp_dui', models.BigIntegerField()),
                ('nit', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_administrador', models.CharField(max_length=20)),
                ('cod_escuela', models.ForeignKey(db_column='cod_escuela', on_delete=django.db.models.deletion.DO_NOTHING, to='GestionLocales.escuela')),
            ],
            options={
                'db_table': 'administrador',
                'managed': True,
                'unique_together': {('dui', 'emp_dui')},
            },
        ),
    ]
