# Generated by Django 3.2.7 on 2021-10-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0002_auto_20211019_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='fecha_nacimiento',
            field=models.DateField(db_column='fecha_nacimiento', null=True),
        ),
    ]
