# Generated by Django 3.2.7 on 2021-10-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0003_administrador_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='cod_notificacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
