# Generated by Django 3.2.7 on 2021-10-17 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0003_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nit',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='dui',
        ),
        migrations.AddField(
            model_name='administrador',
            name='cod_empleado',
            field=models.ForeignKey(db_column='cod_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administrador',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='cod_empleado',
            field=models.ForeignKey(db_column='cod_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='docente',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='cod_empleado',
            field=models.ForeignKey(db_column='cod_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='administrador',
            unique_together={('dui', 'cod_empleado')},
        ),
        migrations.AlterUniqueTogether(
            name='docente',
            unique_together={('dui', 'cod_empleado')},
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='codigo_administrador',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='emp_dui',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='password',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='codigo_docente',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='emp_dui',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='password',
        ),
    ]
