# Generated by Django 3.2.7 on 2021-10-19 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLocales', '0001_initial'),
        ('GestionUsuarios', '0004_auto_20211017_0125'),
    ]

    operations = [
        
        
        migrations.AlterField(
            model_name='empleado',
            name='dui',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='administrador',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='docente',
            unique_together=set(),
        ),
      
    ]
