# Generated by Django 3.2.7 on 2021-10-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0004_alter_notificacion_cod_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
