# Generated by Django 3.2.7 on 2021-11-05 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0001_initial'),
        ('GestionMaterias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espartede',
            name='coordinador',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='espartede',
            name='dui',
            field=models.ForeignKey(db_column='dui', default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.docente'),
            preserve_default=False,
        ),
    ]
