# Generated by Django 3.2.7 on 2021-11-02 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionMaterias', '0001_initial'),
        ('GestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espartede',
            name='dui',
            field=models.ForeignKey(db_column='dui', on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.docente'),
        ),
        migrations.AddField(
            model_name='catedra',
            name='cod_materia',
            field=models.ForeignKey(db_column='cod_materia', null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionMaterias.materia'),
        ),
        migrations.AddField(
            model_name='catedra',
            name='docentes',
            field=models.ManyToManyField(through='GestionMaterias.EsParteDe', to='GestionUsuarios.Docente'),
        ),
        migrations.AddField(
            model_name='requisitode',
            name='cod_materia',
            field=models.ForeignKey(db_column='cod_materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='GestionMaterias.materia'),
        ),
        migrations.AlterUniqueTogether(
            name='imparte',
            unique_together={('numero_de_ciclo', 'cod_materia', 'cod_pensum')},
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('cod_hora', 'cod_dia')},
        ),
        migrations.AlterUniqueTogether(
            name='espartede',
            unique_together={('dui', 'cod_catedra')},
        ),
        migrations.AlterUniqueTogether(
            name='catedra',
            unique_together={('cod_materia', 'anio', 'ciclo_par')},
        ),
        migrations.AlterUniqueTogether(
            name='requisitode',
            unique_together={('mat_cod_materia', 'cod_materia')},
        ),
    ]
