# Generated by Django 3.2.7 on 2021-10-17 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLocales', '0002_auto_20211017_0220'),
        ('GestionUsuarios', '0002_administrador_docente_notificacion'),
        ('GestionMaterias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='id',
        ),
        migrations.AddField(
            model_name='catedra',
            name='cod_materia',
            field=models.ForeignKey(db_column='cod_materia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionMaterias.materia'),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='cod_pensum',
            field=models.OneToOneField(db_column='cod_pensum', default='ISI', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='GestionMaterias.pensum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='espartede',
            name='cod_catedra',
            field=models.ForeignKey(db_column='cod_catedra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionMaterias.catedra'),
        ),
        migrations.AddField(
            model_name='imparte',
            name='cod_materia',
            field=models.ForeignKey(db_column='cod_materia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionMaterias.materia'),
        ),
        migrations.AddField(
            model_name='pensum',
            name='cod_escuela',
            field=models.ForeignKey(blank=True, db_column='cod_escuela', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionLocales.escuela'),
        ),
        migrations.AddField(
            model_name='requisitode',
            name='cod_materia',
            field=models.ForeignKey(db_column='cod_materia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cod_materia_RquisitoDe', to='GestionMaterias.materia'),
        ),
        migrations.AlterUniqueTogether(
            name='espartede',
            unique_together={('dui', 'cod_catedra')},
        ),
        migrations.AlterUniqueTogether(
            name='imparte',
            unique_together={('numero_de_ciclo', 'cod_materia')},
        ),
        migrations.AlterUniqueTogether(
            name='requisitode',
            unique_together={('mat_cod_materia', 'cod_materia')},
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('cod_horario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cod_dia', models.ForeignKey(db_column='cod_dia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionMaterias.dia')),
                ('cod_hora', models.ForeignKey(db_column='cod_hora', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionMaterias.hora')),
            ],
            options={
                'db_table': 'horario',
                'managed': True,
            },
        ),
    ]
