# Generated by Django 3.2.7 on 2021-10-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMaterias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hora',
            name='cod_hora',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hora',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='hora',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='hora',
            unique_together={('hora_inicio', 'hora_fin')},
        ),
    ]
