# Generated by Django 3.2.7 on 2021-11-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0001_initial'),
        ('GestionMaterias', '0002_auto_20211105_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='catedra',
            name='docentes',
            field=models.ManyToManyField(through='GestionMaterias.EsParteDe', to='GestionUsuarios.Docente'),
        ),
    ]
