# Generated by Django 3.2.7 on 2021-10-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMaterias', '0002_alter_requisitode_cod_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espartede',
            name='coordinador',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
