# Generated by Django 3.2.7 on 2021-11-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMaterias', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='ciclo_par',
        ),
    ]
