# Generated by Django 3.2.7 on 2021-10-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMaterias', '0003_alter_horario_cod_horario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('cod_hora', 'cod_dia')},
        ),
    ]
