# Generated by Django 3.2.7 on 2021-10-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMaterias', '0003_alter_espartede_coordinador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catedra',
            name='cod_catedra',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
