# Generated by Django 3.2.7 on 2021-11-06 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMaterias', '0003_remove_ciclo_ciclo_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensum',
            name='anio_publicacion',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1950), django.core.validators.MinValueValidator(2021)]),
        ),
    ]
