# Generated by Django 3.2.7 on 2021-11-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMaterias', '0004_alter_pensum_anio_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imparte',
            name='numero_de_ciclo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
