# Generated by Django 3.2.7 on 2021-10-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMaterias', '0004_alter_catedra_cod_catedra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catedra',
            name='ciclo_par',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
