# Generated by Django 3.2.7 on 2021-10-31 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0006_auto_20211023_0341'),
        ('GestionMaterias', '0005_alter_catedra_ciclo_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='espartede',
            name='cod_empleado',
            field=models.ForeignKey(db_column='cod_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empleado', to='GestionUsuarios.docente'),
        ),
        migrations.AlterUniqueTogether(
            name='espartede',
            unique_together={('dui', 'cod_catedra')},
        ),
        migrations.RemoveField(
            model_name='espartede',
            name='emp_dui',
        ),
    ]
