# Generated by Django 3.2.7 on 2021-10-31 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMaterias', '0006_auto_20211030_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espartede',
            name='cod_empleado',
        ),
    ]
