# Generated by Django 3.2.7 on 2021-10-31 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLocales', '0007_local_url_img'),
        ('GestionUsuarios', '0006_auto_20211023_0341'),
        ('GestionMaterias', '0007_remove_espartede_cod_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catedra',
            name='cod_materia',
            field=models.ForeignKey(db_column='cod_materia', null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionMaterias.materia'),
        ),
        migrations.AlterField(
            model_name='espartede',
            name='cod_catedra',
            field=models.ForeignKey(db_column='cod_catedra', null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionMaterias.catedra'),
        ),
        migrations.AlterField(
            model_name='espartede',
            name='dui',
            field=models.OneToOneField(db_column='dui', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='GestionUsuarios.docente'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='cod_dia',
            field=models.ForeignKey(db_column='cod_dia', null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionMaterias.dia'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='cod_hora',
            field=models.ForeignKey(db_column='cod_hora', null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionMaterias.hora'),
        ),
        migrations.AlterField(
            model_name='imparte',
            name='cod_materia',
            field=models.ForeignKey(db_column='cod_materia', null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionMaterias.materia'),
        ),
        migrations.AlterField(
            model_name='pensum',
            name='cod_escuela',
            field=models.ForeignKey(blank=True, db_column='cod_escuela', null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionLocales.escuela'),
        ),
        migrations.AlterField(
            model_name='requisitode',
            name='cod_materia',
            field=models.ForeignKey(db_column='cod_materia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='GestionMaterias.materia'),
        ),
        migrations.AlterField(
            model_name='requisitode',
            name='mat_cod_materia',
            field=models.OneToOneField(db_column='mat_cod_materia', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='GestionMaterias.materia'),
        ),
    ]
