# Generated by Django 3.2.7 on 2021-10-31 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMaterias', '0008_auto_20211031_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imparte',
            name='cod_pensum',
            field=models.ForeignKey(db_column='cod_pensum', on_delete=django.db.models.deletion.CASCADE, to='GestionMaterias.pensum'),
        ),
    ]
