# Generated by Django 3.2.7 on 2021-10-13 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionLocales', '0001_initial'),
        ('GestionUsuarios', '0001_initial'),
        ('GestionMaterias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('cod_reserva', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cod_horario', models.BigIntegerField()),
                ('adm_dui', models.BigIntegerField()),
                ('estado_solicitud', models.CharField(max_length=20)),
                ('fecha_envio', models.DateField()),
                ('fecha_aprobacion', models.DateField()),
                ('adm_emp_dui', models.ForeignKey(db_column='adm_emp_dui', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adm_emp_dui_Reserva', to='GestionUsuarios.administrador')),
                ('cod_local', models.ForeignKey(blank=True, db_column='cod_local', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionLocales.local')),
                ('cod_materia', models.ForeignKey(blank=True, db_column='cod_materia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionMaterias.materia')),
                ('doc_dui', models.ForeignKey(db_column='doc_dui', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_dui_Reserva', to='GestionUsuarios.docente')),
                ('dui', models.ForeignKey(db_column='dui', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionUsuarios.administrador')),
                ('emp_dui', models.ForeignKey(db_column='emp_dui', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionUsuarios.docente')),
            ],
            options={
                'db_table': 'reserva',
                'managed': True,
            },
        ),
    ]
