# Generated by Django 3.2.7 on 2021-10-17 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionUsuarios', '0002_administrador_docente_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('cod_reserva', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cod_horario', models.BigIntegerField()),
                ('estado_solicitud', models.CharField(max_length=20)),
                ('fecha_envio', models.DateField()),
                ('fecha_aprobacion', models.DateField()),
                ('adm_dui', models.ForeignKey(db_column='dui', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionUsuarios.administrador')),
                ('doc_dui', models.ForeignKey(db_column='doc_dui', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_dui_Reserva', to='GestionUsuarios.docente')),
            ],
            options={
                'db_table': 'reserva',
                'managed': True,
            },
        ),
    ]
