# Generated by Django 3.2.9 on 2021-11-28 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionUsuarios', '0001_initial'),
        ('GestionMaterias', '0002_initial'),
        ('GestionReservas', '0001_initial'),
        ('GestionLocales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='adm_cod_empleado',
            field=models.ForeignKey(db_column='adm_cod_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adm_cod_empleado_Reserva', to='GestionUsuarios.administrador'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cod_horario',
            field=models.ForeignKey(db_column='cod_horario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionMaterias.horario'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cod_local',
            field=models.ForeignKey(db_column='cod_local', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionLocales.local'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cod_materia',
            field=models.ForeignKey(db_column='cod_materia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionMaterias.materia'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='doc_dui',
            field=models.ForeignKey(db_column='doc_dui', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservas_realizadas', to='GestionUsuarios.docente'),
        ),
    ]
