# Generated by Django 3.2.7 on 2021-10-17 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionReservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='adm_dui',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='dui',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='emp_dui',
        ),
    ]
