# Generated by Django 3.2.7 on 2021-10-17 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMaterias', '0002_auto_20211017_0220'),
        ('GestionLocales', '0002_auto_20211017_0220'),
        ('GestionReservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cod_local',
            field=models.ForeignKey(blank=True, db_column='cod_local', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionLocales.local'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cod_materia',
            field=models.ForeignKey(blank=True, db_column='cod_materia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionMaterias.materia'),
        ),
    ]
