# Generated by Django 3.2.7 on 2021-10-20 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0001_initial'),
        ('GestionMaterias', '0001_initial'),
        ('GestionLocales', '0002_auto_20211019_1809'),
        ('GestionReservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='adm_emp_dui',
            field=models.ForeignKey(db_column='adm_emp_dui', default='1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='adm_emp_dui_Reserva', to='GestionUsuarios.administrador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='cod_horario',
            field=models.ForeignKey(db_column='cod_horario', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='GestionMaterias.horario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='cod_local',
            field=models.ForeignKey(db_column='cod_local', default='06:00:00', on_delete=django.db.models.deletion.DO_NOTHING, to='GestionLocales.local'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='cod_materia',
            field=models.ForeignKey(db_column='cod_materia', default='', on_delete=django.db.models.deletion.DO_NOTHING, to='GestionMaterias.materia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='doc_dui',
            field=models.ForeignKey(db_column='doc_dui', default='483299843', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservas_realizadas', to='GestionUsuarios.docente'),
            preserve_default=False,
        ),
    ]
