# Generated by Django 3.2.7 on 2021-11-06 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMaterias', '0003_remove_ciclo_ciclo_par'),
        ('GestionLocales', '0003_puntuacion_puntuacion'),
        ('GestionReservas', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('cod_horario', 'cod_local')},
        ),
    ]
