# Generated by Django 3.2.7 on 2021-10-21 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLocales', '0002_auto_20211019_1809'),
        ('GestionUsuarios', '0003_administrador_fecha_nacimiento'),
        ('GestionMaterias', '0002_alter_requisitode_cod_materia'),
        ('GestionReservas', '0002_auto_20211019_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='adm_emp_dui',
            field=models.ForeignKey(db_column='adm_emp_dui', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adm_emp_dui_Reserva', to='GestionUsuarios.administrador'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cod_horario',
            field=models.ForeignKey(db_column='cod_horario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionMaterias.horario'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cod_local',
            field=models.ForeignKey(db_column='cod_local', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionLocales.local'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cod_materia',
            field=models.ForeignKey(db_column='cod_materia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionMaterias.materia'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='doc_dui',
            field=models.ForeignKey(db_column='doc_dui', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservas_realizadas', to='GestionUsuarios.docente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_envio',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
