# Generated by Django 3.2.7 on 2021-10-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMaterias', '0004_alter_horario_unique_together'),
        ('GestionLocales', '0001_initial'),
        ('GestionUsuarios', '0004_auto_20211017_0125'),
        ('GestionReservas', '0002_auto_20211017_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='adm_emp_dui',
            field=models.ForeignKey(db_column='adm_emp_dui', default='038984424', on_delete=django.db.models.deletion.DO_NOTHING, related_name='adm_emp_dui_Reserva', to='GestionUsuarios.administrador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cod_horario',
            field=models.ForeignKey(db_column='cod_horario', on_delete=django.db.models.deletion.DO_NOTHING, to='GestionMaterias.horario'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cod_local',
            field=models.ForeignKey(db_column='cod_local', default='LCOMP', on_delete=django.db.models.deletion.DO_NOTHING, to='GestionLocales.local'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cod_materia',
            field=models.ForeignKey(db_column='cod_materia', default='TOO115', on_delete=django.db.models.deletion.DO_NOTHING, to='GestionMaterias.materia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cod_reserva',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='doc_dui',
            field=models.ForeignKey(db_column='doc_dui', default='094839486', on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_dui_Reserva', to='GestionUsuarios.docente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_envio',
            field=models.DateField(auto_now=True),
        ),
    ]
