# Generated by Django 3.2.7 on 2021-10-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionReservas', '0003_auto_20211021_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado_solicitud',
            field=models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('EN_PROCESO', 'En Proceso'), ('ACEPTADA', 'Aceptada'), ('DENEGADA', 'Denegada'), ('PENDIENTE', 'Pendiente')], max_length=20),
        ),
    ]
