# Generated by Django 3.2.7 on 2021-10-31 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0006_auto_20211023_0341'),
        ('GestionReservas', '0004_alter_reserva_estado_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='adm_emp_dui',
        ),
        migrations.AddField(
            model_name='reserva',
            name='adm_cod_empleado',
            field=models.ForeignKey(db_column='adm_cod_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adm_cod_empleado_Reserva', to='GestionUsuarios.administrador'),
        ),
    ]
