# Generated by Django 3.2.7 on 2021-10-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('dui', models.BigIntegerField(primary_key=True, serialize=False)),
                ('emp_dui', models.BigIntegerField()),
                ('nit', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_administrador', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('dui', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nit', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_dui', models.BigIntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('codigo_docente', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('cod_notificacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dui', models.BigIntegerField(blank=True, null=True)),
                ('visto', models.BigIntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.DateField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
    ]
