# Generated by Django 3.2.7 on 2021-11-02 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('cod_edificio', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_edificio', models.CharField(max_length=256)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'edificio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('cod_escuela', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_escuela', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'escuela',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('cod_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=256, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='templates/build/static/media')),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'imagen',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('cod_local', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_local', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=256)),
                ('nivel', models.BigIntegerField()),
                ('altitud', models.FloatField(blank=True, null=True)),
                ('puntuacion', models.FloatField(blank=True, null=True)),
                ('imagen_local', models.ImageField(null=True, upload_to='templates/build/static/media')),
                ('url_img', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'local',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_local', models.ForeignKey(db_column='cod_local', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='puntuaciones_docentes', to='GestionLocales.local')),
            ],
            options={
                'db_table': 'puntuacion',
                'managed': True,
            },
        ),
    ]
