# Generated by Django 3.2.7 on 2021-10-13 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('cod_edificio', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_edificio', models.CharField(max_length=50)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'edificio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('cod_escuela', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_escuela', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'escuela',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('cod_local', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_local', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('nivel', models.BigIntegerField()),
                ('altitud', models.FloatField(blank=True, null=True)),
                ('puntuacion', models.FloatField(blank=True, null=True)),
                ('cod_edificio', models.ForeignKey(db_column='cod_edificio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionLocales.edificio')),
            ],
            options={
                'db_table': 'local',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('cod_imagen', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=256, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_local', models.ForeignKey(db_column='cod_local', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionLocales.local')),
            ],
            options={
                'db_table': 'imagen',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='edificio',
            name='cod_escuela',
            field=models.ForeignKey(db_column='cod_escuela', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionLocales.escuela'),
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('dui', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cod_local', models.ForeignKey(db_column='cod_local', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cod_local_Puntuacion', to='GestionLocales.local')),
            ],
            options={
                'db_table': 'puntuacion',
                'managed': True,
                'unique_together': {('dui', 'cod_local')},
            },
        ),
    ]
