# Generated by Django 3.2.7 on 2021-11-05 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0001_initial'),
        ('GestionLocales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntuacion',
            name='dui',
            field=models.ForeignKey(db_column='doc_dui', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='puntuaciones', to='GestionUsuarios.docente'),
        ),
        migrations.AlterUniqueTogether(
            name='puntuacion',
            unique_together={('dui', 'cod_local')},
        ),
    ]
