# Generated by Django 3.2.7 on 2021-10-20 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0001_initial'),
        ('GestionLocales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='cod_escuela',
            field=models.ForeignKey(db_column='cod_escuela', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionLocales.escuela'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='cod_local',
            field=models.ForeignKey(db_column='cod_local', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionLocales.local'),
        ),
        migrations.AddField(
            model_name='local',
            name='cod_edificio',
            field=models.ForeignKey(db_column='cod_edificio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionLocales.edificio'),
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_local', models.ForeignKey(db_column='cod_local', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='puntuaciones_docentes', to='GestionLocales.local')),
                ('dui', models.ForeignKey(db_column='doc_dui', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='puntuaciones', to='GestionUsuarios.docente')),
            ],
            options={
                'db_table': 'puntuacion',
                'managed': True,
                'unique_together': {('dui', 'cod_local')},
            },
        ),
    ]
