# Generated by Django 3.2.7 on 2021-11-02 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionLocales', '0001_initial'),
        ('GestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntuacion',
            name='dui',
            field=models.ForeignKey(db_column='doc_dui', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='puntuaciones', to='GestionUsuarios.docente'),
        ),
        migrations.AddField(
            model_name='local',
            name='cod_edificio',
            field=models.ForeignKey(db_column='cod_edificio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionLocales.edificio'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='cod_local',
            field=models.ForeignKey(db_column='cod_local', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionLocales.local'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='cod_escuela',
            field=models.ForeignKey(db_column='cod_escuela', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestionLocales.escuela'),
        ),
        migrations.AlterUniqueTogether(
            name='puntuacion',
            unique_together={('dui', 'cod_local')},
        ),
    ]
