# Generated by Django 3.2.7 on 2021-10-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLocales', '0002_auto_20211019_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='nombre_edificio',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='nombre_escuela',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='local',
            name='descripcion',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='local',
            name='nombre_local',
            field=models.CharField(max_length=100),
        ),
    ]
