# Generated by Django 3.2.7 on 2021-11-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLocales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntuacion',
            name='puntuacion',
            field=models.IntegerField(null=True),
        ),
    ]
