# Generated by Django 3.2.7 on 2021-10-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLocales', '0002_auto_20211017_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='nombre_escuela',
            field=models.CharField(max_length=255),
        ),
    ]
