# Generated by Django 3.2.7 on 2021-10-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLocales', '0004_auto_20211028_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='cod_imagen',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
