# Generated by Django 3.2.7 on 2021-10-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionLocales', '0005_alter_imagen_cod_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='imagen_local',
            field=models.ImageField(null=True, upload_to='templates/build/static/media'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(null=True, upload_to='templates/build/static/media'),
        ),
    ]
